export enum AssetType {
	// Avo
	ASSIGNMENT_DESCRIPTION_IMAGE = 'ASSIGNMENT_DESCRIPTION_IMAGE',
	BUNDLE_COVER = 'BUNDLE_COVER',
	BUNDLE_OG_IMAGE = 'BUNDLE_OG_IMAGE',
	COLLECTION_COVER = 'COLLECTION_COVER',
	COLLECTION_OG_IMAGE = 'COLLECTION_OG_IMAGE',
	ASSIGNMENT_OG_IMAGE = 'ASSIGNMENT_OG_IMAGE',
	CONTENT_BLOCK_FILE = 'CONTENT_BLOCK_FILE',
	CONTENT_BLOCK_IMAGE = 'CONTENT_BLOCK_IMAGE',
	CONTENT_PAGE_COVER = 'CONTENT_PAGE_COVER',
	CONTENT_PAGE_OG_IMAGE = 'CONTENT_PAGE_OG_IMAGE',
	CONTENT_PAGE_DESCRIPTION_IMAGE = 'CONTENT_PAGE_DESCRIPTION_IMAGE',
	INTERACTIVE_TOUR_IMAGE = 'INTERACTIVE_TOUR_IMAGE',
	ITEM_NOTE_IMAGE = 'ITEM_NOTE_IMAGE',
	ITEM_SUBTITLE = 'ITEM_SUBTITLE',
	ITEM_OG_IMAGE = 'ITEM_OG_IMAGE',
	PROFILE_AVATAR = 'PROFILE_AVATAR',
	KLASCEMENT_VIDEO_IMAGE = 'KLASCEMENT_VIDEO_IMAGE',
	ZENDESK_ATTACHMENT = 'ZENDESK_ATTACHMENT',

	// Archief
	SPACE_IMAGE = 'SPACE_IMAGE',
	SITEMAP = 'SITEMAP',

	// Avo and Archief
	CONTENT_PAGE_IMAGE = 'CONTENT_PAGE_IMAGE',
}
