export {
	Assignment as AvoAssignmentAssignment,
	AssignmentBlock as AvoAssignmentBlock,
	AssignmentBlockType as AvoAssignmentBlockType,
	AssignmentContent as AvoAssignmentContent,
	AssignmentContentLabel as AvoAssignmentContentLabel,
	AssignmentContributor as AvoAssignmentContributor,
	AssignmentContributorInfo as AvoAssignmentContributorInfo,
	AssignmentLabel as AvoAssignmentLabel,
	AssignmentLabelType as AvoAssignmentLabelType,
	AssignmentQualityLabel as AvoAssignmentQualityLabel,
	AssignmentRelationEntry as AvoAssignmentRelationEntry,
	AssignmentRelationType as AvoAssignmentRelationType,
	AssignmentResponse as AvoAssignmentResponse,
	AssignmentRetrieveError as AvoAssignmentRetrieveError,
	AssignmentType as AvoAssignmentType,
	AssignmentView as AvoAssignmentView,
} from '../modules/assignment.js';
