export {
	Collection as AvoEducationOrganizationCollection,
	CollectionContributor as AvoEducationOrganizationContributor,
	CollectionFragment as AvoEducationOrganizationFragment,
	CollectionFragmentExternalId as AvoEducationOrganizationExternalId,
	CollectionFragmentType as AvoEducationOrganizationBlockType,
	CollectionLabel as AvoEducationOrganizationLabel,
	CollectionManagement as AvoEducationOrganizationManagement,
	CollectionManagementQualityCheck as AvoEducationOrganizationManagementQualityCheck,
	RelationEntry as AvoEducationOrganizationRelationEntry,
	RelationType as AvoEducationOrganizationRelationType,
} from '../modules/collection.js';
