export {
	Assignment,
	AssignmentBlock as Block,
	AssignmentBlockType as BlockType,
	AssignmentContent as Content,
	AssignmentContentLabel as ContentLabel,
	AssignmentContributor as Contributor,
	AssignmentContributorInfo as ContributorInfo,
	AssignmentLabel as Label,
	AssignmentLabelType as LabelType,
	AssignmentQualityLabel as QualityLabel,
	AssignmentRelationEntry as RelationEntry,
	AssignmentRelationType as RelationType,
	AssignmentResponse as Response,
	AssignmentRetrieveError as RetrieveError,
	AssignmentType as Type,
	AssignmentView as View,
} from '../modules/assignment.js';
