export declare enum DatabaseType {
    avo = "avo",
    hetArchief = "hetarchief"
}
export declare enum ContentPickerType {
    CONTENT_PAGE = "CONTENT_PAGE",
    NL_CONTENT_PAGE_PARENT_ID = "NL_CONTENT_PAGE_PARENT_ID",
    INTERNAL_LINK = "INTERNAL_LINK",
    EXTERNAL_LINK = "EXTERNAL_LINK",
    ANCHOR_LINK = "ANCHOR_LINK",
    PROFILE = "PROFILE",
    FILE = "FILE",
    CUSTOM_NAVIGATION_ELEMENTS = "CUSTOM_NAVIGATION_ELEMENTS",

    CONTENT_PAGE_NEWS_ITEM = "CONTENT_PAGE_NEWS_ITEM",
    CONTENT_PAGE_PAGE = "CONTENT_PAGE_PAGE",
    CONTENT_PAGE_PROJECT = "CONTENT_PAGE_PROJECT",
    CONTENT_PAGE_OVERVIEW = "CONTENT_PAGE_OVERVIEW",
    CONTENT_PAGE_DOMAIN_DETAIL = "CONTENT_PAGE_DOMAIN_DETAIL",
    CONTENT_PAGE_EVENT_DETAIL = "CONTENT_PAGE_EVENT_DETAIL",
    CONTENT_PAGE_SCREENCAST = "CONTENT_PAGE_SCREENCAST",
    /**
     * @deprecated use CUSTOM_NAVIGATION_ELEMENTS instead
     */
    DROPDOWN = "DROPDOWN",
    ITEM = "ITEM",
    COLLECTION = "COLLECTION",
    BUNDLE = "BUNDLE",
    ASSIGNMENT = "ASSIGNMENT",
    SEARCH_QUERY = "SEARCH_QUERY",
    PROJECTS = "PROJECTS",
    IE_OBJECT = "IE_OBJECT"
}
