export enum DatabaseType {
	avo = 'avo',
	hetArchief = 'hetarchief',
}

export enum ContentPickerType {
	CONTENT_PAGE = 'CONTENT_PAGE',
	NL_CONTENT_PAGE_PARENT_ID = 'NL_CONTENT_PAGE_PARENT_ID',
	COLLECTION = 'COLLECTION',
	ITEM = 'ITEM',
	BUNDLE = 'BUNDLE',
	ASSIGNMENT = 'ASSIGNMENT',
	INTERNAL_LINK = 'INTERNAL_LINK',
	EXTERNAL_LINK = 'EXTERNAL_LINK',
	SEARCH_QUERY = 'SEARCH_QUERY',
	PROJECTS = 'PROJECTS',
	ANCHOR_LINK = 'ANCHOR_LINK',
	PROFILE = 'PROFILE',
	FILE = 'FILE',
	CUSTOM_NAVIGATION_ELEMENTS = 'CUSTOM_NAVIGATION_ELEMENTS',
	DROPDOWN = 'DROPDOWN',
}
