export enum Idp {
	HETARCHIEF = 'HETARCHIEF',
	SMARTSCHOOL = 'SMARTSCHOOL',
	KLASCEMENT = 'KLASCEMENT',
	VLAAMSEOVERHEID__SUB_ID = 'VLAAMSEOVERHEID__SUB_ID',
	VLAAMSEOVERHEID__ACCOUNT_ID = 'VLAAMSEOVERHEID__ACCOUNT_ID',
}
