export enum Idp {
	HETARCHIEF = 'HETARCHIEF',
	SMARTSCHOOL = 'SMARTSCHOOL',
	KLASCEMENT = 'KLASCEMENT',
	VLAAMSEOVERHEID__SUB_ID = 'VLAAMSEOVERHEID__SUB_ID',
	VLAAMSEOVERHEID__ACCOUNT_ID = 'VLAAMSEOVERHEID__ACCOUNT_ID',

	// LTI flows for embedding videos in external platforms
	LTI_BOOKWIDGETS = 'LTI_BOOKWIDGETS',
	LTI_SMARTSCHOOL = 'LTI_SMARTSCHOOL',
}
