export declare enum Idp {
    HETARCHIEF = "HETARCHIEF",
    SMARTSCHOOL = "SMARTSCHOOL",
    KLASCEMENT = "KLASCEMENT",
    VLAAMSEOVERHEID__SUB_ID = "VLAAMSEOVERHEID__SUB_ID",
    VLAAMSEOVERHEID__ACCOUNT_ID = "VLAAMSEOVERHEID__ACCOUNT_ID",
    LTI_BOOKWIDGETS = "LTI_BOOKWIDGETS",
    LTI_SMARTSCHOOL = "LTI_SMARTSCHOOL"
}
