apiVersion: v1
kind: BuildConfig
metadata:
  labels:
    name: avo2-typings
    app: avo2-typings
  name: avo2-typings-dev
spec:
  source:
    type: Git
    git:
      uri: https://github.com/viaacode/avo2-typings.git

  strategy:
    type: JenkinsPipeline
    jenkinsPipelineStrategy:
      jenkinsfilePath: openshift/Jenkinsfile

